# Generated by Django 5.2.6 on 2025-10-27 03:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Bio', models.TextField(blank=True, null=True)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('DateOfDeath', models.DateField(blank=True, null=True)),
                ('Image', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('GenreID', models.AutoField(primary_key=True, serialize=False)),
                ('GenreName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('ZipCode', models.CharField(max_length=10)),
                ('ProfilePicture', models.CharField(blank=True, max_length=200, null=True)),
                ('DateJoined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('Publisher', models.CharField(blank=True, default='', max_length=200)),
                ('PublicationDate', models.DateField(blank=True, null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('Stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('Photo', models.CharField(blank=True, default='', max_length=200)),
                ('AuthorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('GenreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('OrderStatus', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('OrderItemID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='books.order')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('ReviewText', models.TextField()),
                ('ReviewDate', models.DateTimeField(auto_now_add=True)),
                ('Rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.customer')),
            ],
            options={
                'unique_together': {('CustomerID', 'BookID')},
            },
        ),
    ]
